'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class CreateSurvey

    '''<summary>
    '''btnDynamicSurvey control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnDynamicSurvey As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''btnYesNoSurvey control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnYesNoSurvey As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''btnMCSurvey control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnMCSurvey As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''btnRatingSurvey control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnRatingSurvey As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''btnADSurvey control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnADSurvey As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''btnChainSurvey control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnChainSurvey As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''Create_Survey control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Create_Survey As Global.CodeLogically.CreateNewQuestion

    '''<summary>
    '''btnAddAnother control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnAddAnother As Global.System.Web.UI.WebControls.Button
End Class
