'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class CreateNewQuestion

    '''<summary>
    '''lblQuestionText control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblQuestionText As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtQuestionText control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtQuestionText As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''ddlQuestionType control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlQuestionType As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''chkIDKMyBFFJill control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkIDKMyBFFJill As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''chkMultiLine control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkMultiLine As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''btnAddOption control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnAddOption As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''txtRadioAmount control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtRadioAmount As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''divOptions control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divOptions As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''rptUserOptions control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rptUserOptions As Global.System.Web.UI.WebControls.Repeater

    '''<summary>
    '''RadioButtonsPanel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadioButtonsPanel As Global.System.Web.UI.WebControls.Panel
End Class
