'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class Surveys

    '''<summary>
    '''divSurveyMainPage control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divSurveyMainPage As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''btnCreateSurvey control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnCreateSurvey As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''btnTakeSurvey control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnTakeSurvey As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''Login control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Login As Global.CodeLogically.Login1
End Class
